# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

arc:
  ai:
    clients:
      - id: GPT-4o
        model-name: gpt-4o
        api-key: ${OPENAI_API_KEY}
        client: openai
      - id: llama3:8b
        modelName: llama3:8b
        client: ollama
      - id: GPT-4o-Azure
        model-name: GPT-4o
        url: ${AZURE_OPENAI_URL}
        client: azure