# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

ai:
  clients:
    - model-name: GPT-4o
      url: NOT_REQUIRED_FOR_OPENAI
      api-key: YOUR_API_KEY
      client: azure
    - model-name: gemma:7b
      url: http://localhost:11434
      client: ollama
    - model-name: llava
      url: http://localhost:11434
      client: ollama
    - model-name: llama3:8b
      url: http://localhost:11434
      client: ollama